#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.1                         #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -I../LunaLibs/irrlicht-1.8.4/source/Irrlicht -I../LunaLibs/irrlicht-1.8.4/include -I../LunaLibs/net/irrNetLite22 -I../LunaLibs/freetype-2.3.9/include -I../LunaLibs/net/enet-1.2.1/include -IFileSystem/readblend -I../LunaLibs/libtheora-1.1.1/include/theora -I../LunaLibs/libtheoraplayer/include -I/usr/include/AL -I/usr/include/python -I./entities/AI/recast/RecastDemo/Include -I./entities/AI/recast/DebugUtils/Include -I./entities/AI/recast/Recast/Include -I./entities/AI/recast/Detour/Include -I./entities/AI/recast/DetourCrowd/Include -I./entities/AI/recast/DetourTileCache/Include -I../LunaLibs/libIrrOpenSteer_10-02-15/include -I../LunaLibs/assimp-3.3.1/include -I../LunaLibs/Scripting/sqplus-code/sqplus -I../LunaLibs/Scripting/sqplus-code/include -I../LunaLibs/cAudio23/cAudio/include -I../LunaLibs/cAudio23/include -IScene/SPARK -I../LunaLibs/bullet3-2.86.1/src -I../LunaLibs/media/fluidsynth-emscripten/include -I../LunaLibs/media/fluidsynth-emscripten/ -I../LunaLibs/SparkEngine/src -I../LunaLibs/SparkEngine/include -I../LunaLibs/PolyVox/library/PolyVoxCore/include
CFLAGS = -I/usr/include/atk-1.0 -I/usr/include/pango-1.0 -I/usr/include/pixman-1 `pkg-config gtk+-2.0 --cflags` -DPARTICLES
RESINC = 
LIBDIR = -L../LunaLibs/freetype-2.3.9/objs/.libs -L../LunaLibs/net/enet-1.2.1 -L../LunaLibs/irrlicht-1.8.4/lib/Linux -L../LunaLibs/Compiled/Linux -L../LunaLibs/libtheoraplayer/bin/Linux -L../LunaLibs/net/irrNetLite22 -L../LunaLibs/libIrrOpenSteer_10-02-15/lib -L./entities/AI/recast/DebugUtils/Include/ -L../LunaLibs/assimp-3.3.1/lib -L../LunaLibs/zlib-1.2.3 -L../LunaLibs/libtheoraplayer/ -L../LunaLibs/cAudio23/cAudio/bin/gcc -L../LunaLibs/bullet3-2.86.1/src/BulletDynamics -L../LunaLibs/bullet3-2.86.1/src/BulletSoftBody -L../LunaLibs/bullet3-2.86.1/src/BulletCollision -L../LunaLibs/bullet3-2.86.1/src/LinearMath -L../LunaLibs/SparkEngine/lib/Linux/static -L../LunaLibs/PolyVox/library/PolyVoxCore -L../LunaLibs/media/fluidsynth-emscripten/src
LIB = -lGL -lfluidsynth -lopenal -lXxf86vm -lX11 -lirrNetLite22 -lenet python2.7 -lIrrOpenSteer -lpthread -ltheora -ltheoraplayer -lassimp -lusb -lboost_thread -lboost_system -lsqlite3 -lasound -ljack -logg -lvorbis -lvorbisfile -lcAudio -lpulse -lreadline -lsndfile -lpulse-simple gmodule-2.0 -ldbus-1 -lPolyVoxCore -lIrrlicht -lBulletSoftBody -lBulletDynamics -lBulletCollision -lLinearMath -lfreetype -lz -ldl -lSPARK -lSPARK_IRR
LDFLAGS = `pkg-config gtk+-2.0 --libs`

INC_LINUX_DEBUG = $(INC)
CFLAGS_LINUX_DEBUG = $(CFLAGS) -fpermissive -DPYTHON
RESINC_LINUX_DEBUG = 
RCFLAGS_LINUX_DEBUG = $(RCFLAGS)
LIBDIR_LINUX_DEBUG = $(LIBDIR)
LIB_LINUX_DEBUG = $(LIB)
LDFLAGS_LINUX_DEBUG = $(LDFLAGS)
OBJDIR_LINUX_DEBUG = .dobjs
DEP_LINUX_DEBUG = 
OUT_LINUX_DEBUG = ./GAME/Luna

INC_LINUX_RELEASE = $(INC)
CFLAGS_LINUX_RELEASE = $(CFLAGS) -O2 -fpermissive -DNDEBUG -DPYTHON
RESINC_LINUX_RELEASE = $(RESINC)
RCFLAGS_LINUX_RELEASE = $(RCFLAGS)
LIBDIR_LINUX_RELEASE = $(LIBDIR)
LIB_LINUX_RELEASE = $(LIB)
LDFLAGS_LINUX_RELEASE = $(LDFLAGS) -s
OBJDIR_LINUX_RELEASE = .robjs
DEP_LINUX_RELEASE = 
OUT_LINUX_RELEASE = ./GAME/dLuna

INC_WINDEBUG = -I../libs/pthreads-w32-2-8-0-release -I../libs/bullet-2.75/src -I../libs/libogg-1.1.4/include -I../libs/libvorbis-1.2.3/include -I../libs/freetype-2.3.9/include -IC:/Program Files/OpenAL 1.1 SDK -I../libs/net/enet-1.2.1/include -I../libs/net/irrNetLite21 -I../libs/ffmpeg-0.5/libavcodec -I../libs/ffmpeg-0.5/libavdevice -I../libs/ffmpeg-0.5/ -I../libs/ffmpeg-0.5/libavformat -I../libs/ffmpeg-0.5/libswscale -IC:/Program Files/Python2.6/include -I../libs/cAudio2/include -I../libs/net/syncsys/include -I../libs/angelscript/include -I../libs/angelscript -I../libs/SparkEngine/include
CFLAGS_WINDEBUG = $(CFLAGS)
RESINC_WINDEBUG = $(RESINC)
RCFLAGS_WINDEBUG = $(RCFLAGS)
LIBDIR_WINDEBUG = -L../libs/bullet-2.75/out/release71/libs -L../libs/irrlicht-1.6/lib/Win32-gcc -LC:/Program Files/OpenAL 1.1 SDK/libs/Win32 -L../libs/libogg-1.1.4/ -L../libs/libvorbis-1.2.3/ -L../libs/freetype-2.3.9 -L../libs/pthreads-w32-2-8-0-release -L../libs/net/irrNetLite21 -L../libs/net/enet-1.2.1 -LC:/Program Files/Python2.6/libs -LC:/Dev/Agnostic/Libs/bullet/out/release8/libs -L../libs/net/enet-1.2/bin/Debug -L../libs/cAudio2/bin/win32-gcc -L../libs/angelscript -L../libs/zlib-1.2.3 -L../libs/SparkEngine/lib/mingw/static
LIB_WINDEBUG = $(LIB)-lOpenAL32 -lWSock32 -lWinmm -lpython26 -lpthreads -lcAudio
LDFLAGS_WINDEBUG = $(LDFLAGS)
OBJDIR_WINDEBUG = .objs
DEP_WINDEBUG = 
OUT_WINDEBUG = ./GAME/Luna_win.exe

INC_WINRELEASE = $(INC) -I../libs/pthreads-w32-2-8-0-release -I../libs/bullet/src -I../libs/libogg-1.1.4/include -I../libs/libvorbis-1.2.3/include -I../libs/freetype-2.3.9/include -IC:/Program Files/OpenAL 1.1 SDK -I../libs/net/enet-1.2.1/include -I../libs/net/irrNetLite21 -I../libs/ffmpeg-0.5/libavcodec -I../libs/ffmpeg-0.5/libavdevice -I../libs/ffmpeg-0.5/ -I../libs/ffmpeg-0.5/libavformat -I../libs/ffmpeg-0.5/libswscale -IC:/Program Files/Python2.6/include -I../libs/cAudio2/include
CFLAGS_WINRELEASE = $(CFLAGS) -march=pentium3 -O2 -DNDEBUG
RESINC_WINRELEASE = $(RESINC)
RCFLAGS_WINRELEASE = $(RCFLAGS)
LIBDIR_WINRELEASE = $(LIBDIR) -L../libs/bullet/out/release8/libs -LC:/Program Files/OpenAL 1.1 SDK/libs/Win32 -L../libs/libogg-1.1.4/ -L../libs/libvorbis-1.2.3/ -L../libs/freetype-2.3.9 -L../libs/pthreads-w32-2-8-0-release -L../libs/net/irrNetLite21 -L../libs/net/enet-1.2.1/bin/Release -LC:/Program Files/Python2.6/libs -LC:/Dev/Agnostic/Libs/bullet/out/release8/libs -L../libs/net/enet-1.2/bin/Debug
LIB_WINRELEASE = $(LIB)-lOpenAL32 -lWSock32 -lWinmm -lpython26 -lirrnet -lpthreads -lcAudio
LDFLAGS_WINRELEASE = $(LDFLAGS) -s
OBJDIR_WINRELEASE = .objs
DEP_WINRELEASE = 
OUT_WINRELEASE = ./GAME/Azadi.exe

INC_MINEDBG = $(INC)
CFLAGS_MINEDBG = $(CFLAGS) -fpermissive -DPYTHON -DPHYSICS
RESINC_MINEDBG = 
RCFLAGS_MINEDBG = $(RCFLAGS)
LIBDIR_MINEDBG = $(LIBDIR)
LIB_MINEDBG = $(LIB)-lGL -lfluidsynth -lopenal -lXxf86vm -lX11 -ldl -lirrNetLite22 -lenet -lpython2.7 -lIrrOpenSteer -lpthread -ltheora -ltheoraplayer -lassimp -lusb -lboost_thread -lboost_system -lsqlite3 -lasound -ljack -lreadline -lsndfile -lpulse -lpulse-simple -lgmodule-2.0 -ldbus-1 -lPolyVoxCore -lIrrlicht -lBulletSoftBody -lBulletDynamics -lBulletCollision -lLinearMath -lfreetype -lz -logg -lvorbis -lvorbisfile -lcAudio -lSPARK -lSPARK_IRR
LDFLAGS_MINEDBG =  `pkg-config gtk+-2.0 --libs`
OBJDIR_MINEDBG = .mdobjs
DEP_MINEDBG = 
OUT_MINEDBG = ./GAME/mdLuna

INC_MINEREL = $(INC)
CFLAGS_MINEREL = $(CFLAGS) -fpermissive -DNDEBUG -DPYTHON
RESINC_MINEREL = 
RCFLAGS_MINEREL = $(RCFLAGS)
LIBDIR_MINEREL = $(LIBDIR)
LIB_MINEREL = $(LIB)-lGL -lopenal -lXxf86vm -lX11 -ldl -lirrNetLite22 -lenet -lpython2.7 -lIrrOpenSteer -lpthread -ltheora -ltheoraplayer -lassimp -lusb -lboost_thread -lboost_system -lfluidsynth -lreadline -lsndfile -lpulse -lpulse-simple -lsqlite3
LDFLAGS_MINEREL = $(LDFLAGS)
OBJDIR_MINEREL = .mobjs
DEP_MINEREL = 
OUT_MINEREL = ./GAME/mLuna

INC_1_7_3_DEBUG = $(INC) -I../libs/ffmpeg/libavcodec -I../libs/ffmpeg/libavformat -I../libs/ffmpeg -I../libs/ffmpeg/libswscale -I../libs/ffmpeg/libavutil -I../libs/ffmpeg/libavdevice -I/home/Dev/libs/game/irrlicht/irrlicht-1.7.3/source/irrlicht -I/home/Dev/libs/game/irrlicht/irrlicht-1.7.3/include -I../libs/net/irrNetLite21 -I../libs/net/enet/include -I/home/Dev/libs/physics/bullet-2.75/src -I../libs/freetype-2.3.9/include -I../libs/net/enet-1.2.1 -IFileSystem/readblend -I../libs/cAudio2/include -I../libs/libtheora-1.1.1/include/theora -I/home/Dev/libs/Media/libtheoraplayer/include -I/usr/include/AL -I/home/Dev/libs/Media/cAudio/cAudio/cAudio/include -I/usr/include/python2.7 -I./entities/AI/recast/RecastDemo/Include -I./entities/AI/recast/DebugUtils/Include -I./entities/AI/recast/Recast/Include -I./entities/AI/recast/Detour/Include -I./entities/AI/recast/DetourCrowd/Include -I./entities/AI/recast/DetourTileCache/Include -I../libs/libIrrOpenSteer_10-02-15/include
CFLAGS_1_7_3_DEBUG = $(CFLAGS) -fpermissive -Dirrlicht17
RESINC_1_7_3_DEBUG = 
RCFLAGS_1_7_3_DEBUG = $(RCFLAGS)
LIBDIR_1_7_3_DEBUG = $(LIBDIR) -L/home/Dev/libs/scripting/Python-2.6.2/Lib -L../libs/ffmpeg/libavcodec -L../libs/ffmpeg/libavformat -L../libs/ffmpeg/libswscale -L../libs/ffmpeg/libavutil -L../libs/ffmpeg/libavdevice -L../libs/freetype-2.3.9/objs/.libs -L../libs/net/enet-1.2.1 -L/home/Dev/libs/physics/bullet-2.75/src/BulletDynamics -L/home/Dev/libs/physics/bullet-2.75/src/BulletSoftBody -L/home/Dev/libs/physics/bullet-2.75/src/BulletCollision -L/home/Dev/libs/physics/bullet-2.75/src/LinearMath -L../libs/Compiled/Linux -L/home/Dev/libs/Media/libtheoraplayer/bin/ -L/home/Dev/libs/Media/cAudio/cAudio/cAudio -L../libs/net/irrNetLite21 -L../libs/RecastNavigation/DebugUtils/ -L../libs/RecastNavigation/Recast -L../libs/RecastNavigation/DetourCrowd -L../libs/RecastNavigation/DetourTileCache -L../libs/RecastNavigation/Detour -L../libs/libIrrOpenSteer_10-02-15/lib -L/home/Dev/libs/game/irrlicht/irrlicht-1.7.3 -L/home/Dev/libs/game/irrlicht/irrlicht-1.7.3/lib/Linux
LIB_1_7_3_DEBUG = $(LIB)-lGL -lcAudio -lopenal -lavutil -ltheora -ltheoraplayer -lXxf86vm -lpthread -lXcursor -lX11 -ldl -lirrnet -lenet -lpython2.7 -lRecast -lDetour -lDebugUtils -lDetourCrowd -lDetourTileCache -lIrrOpenSteer
LDFLAGS_1_7_3_DEBUG = $(LDFLAGS) --preload-file GAME/RACING/racer/
OBJDIR_1_7_3_DEBUG = .173mdobjs
DEP_1_7_3_DEBUG = 
OUT_1_7_3_DEBUG = ../mdLuna173

OBJ_LINUX_DEBUG = $(OBJDIR_LINUX_DEBUG)/Main.o

OBJ_LINUX_RELEASE = $(OBJDIR_LINUX_RELEASE)/Main.o

OBJ_WINDEBUG = $(OBJDIR_WINDEBUG)/Main.o

OBJ_WINRELEASE = $(OBJDIR_WINRELEASE)/Main.o

OBJ_MINEDBG = $(OBJDIR_MINEDBG)/Main.o

OBJ_MINEREL = $(OBJDIR_MINEREL)/Main.o

OBJ_1_7_3_DEBUG = $(OBJDIR_1_7_3_DEBUG)/Main.o

all: linux_debug linux_release windebug winrelease minedbg minerel 1_7_3_debug emscripten_debug emscripten_projects emscripten_projects_testing emscripten_projects_testing_nopy emminimal

clean: clean_linux_debug clean_linux_release clean_windebug clean_winrelease clean_minedbg clean_minerel clean_1_7_3_debug clean_emscripten_debug clean_emscripten_projects clean_emscripten_projects_testing clean_emscripten_projects_testing_nopy clean_emminimal

before_linux_debug: 
	test -d ./GAME || mkdir -p ./GAME
	test -d $(OBJDIR_LINUX_DEBUG) || mkdir -p $(OBJDIR_LINUX_DEBUG)

after_linux_debug: 

linux_debug: before_linux_debug out_linux_debug after_linux_debug

out_linux_debug: before_linux_debug $(OBJ_LINUX_DEBUG) $(DEP_LINUX_DEBUG)
	$(LD) $(LIBDIR_LINUX_DEBUG) -o $(OUT_LINUX_DEBUG) $(OBJ_LINUX_DEBUG)  $(LDFLAGS_LINUX_DEBUG) $(LIB_LINUX_DEBUG)

$(OBJDIR_LINUX_DEBUG)/Main.o: Main.cpp
	$(CXX) $(CFLAGS_LINUX_DEBUG) $(INC_LINUX_DEBUG) -c Main.cpp -o $(OBJDIR_LINUX_DEBUG)/Main.o

clean_linux_debug: 
	rm -f $(OBJ_LINUX_DEBUG) $(OUT_LINUX_DEBUG)
	rm -rf ./GAME
	rm -rf $(OBJDIR_LINUX_DEBUG)

before_linux_release: 
	test -d ./GAME || mkdir -p ./GAME
	test -d $(OBJDIR_LINUX_RELEASE) || mkdir -p $(OBJDIR_LINUX_RELEASE)

after_linux_release: 

linux_release: before_linux_release out_linux_release after_linux_release

out_linux_release: before_linux_release $(OBJ_LINUX_RELEASE) $(DEP_LINUX_RELEASE)
	$(LD) $(LIBDIR_LINUX_RELEASE) -o $(OUT_LINUX_RELEASE) $(OBJ_LINUX_RELEASE)  $(LDFLAGS_LINUX_RELEASE) $(LIB_LINUX_RELEASE)

$(OBJDIR_LINUX_RELEASE)/Main.o: Main.cpp
	$(CXX) $(CFLAGS_LINUX_RELEASE) $(INC_LINUX_RELEASE) -c Main.cpp -o $(OBJDIR_LINUX_RELEASE)/Main.o

clean_linux_release: 
	rm -f $(OBJ_LINUX_RELEASE) $(OUT_LINUX_RELEASE)
	rm -rf ./GAME
	rm -rf $(OBJDIR_LINUX_RELEASE)

before_windebug: 
	test -d ./GAME || mkdir -p ./GAME
	test -d $(OBJDIR_WINDEBUG) || mkdir -p $(OBJDIR_WINDEBUG)

after_windebug: 

windebug: before_windebug out_windebug after_windebug

out_windebug: before_windebug $(OBJ_WINDEBUG) $(DEP_WINDEBUG)
	$(LD) $(LIBDIR_WINDEBUG) -o $(OUT_WINDEBUG) $(OBJ_WINDEBUG)  $(LDFLAGS_WINDEBUG) $(LIB_WINDEBUG)

$(OBJDIR_WINDEBUG)/Main.o: Main.cpp
	$(CXX) $(CFLAGS_WINDEBUG) $(INC_WINDEBUG) -c Main.cpp -o $(OBJDIR_WINDEBUG)/Main.o

clean_windebug: 
	rm -f $(OBJ_WINDEBUG) $(OUT_WINDEBUG)
	rm -rf ./GAME
	rm -rf $(OBJDIR_WINDEBUG)

before_winrelease: 
	test -d ./GAME || mkdir -p ./GAME
	test -d $(OBJDIR_WINRELEASE) || mkdir -p $(OBJDIR_WINRELEASE)

after_winrelease: 

winrelease: before_winrelease out_winrelease after_winrelease

out_winrelease: before_winrelease $(OBJ_WINRELEASE) $(DEP_WINRELEASE)
	$(LD) $(LIBDIR_WINRELEASE) -o $(OUT_WINRELEASE) $(OBJ_WINRELEASE)  $(LDFLAGS_WINRELEASE) $(LIB_WINRELEASE)

$(OBJDIR_WINRELEASE)/Main.o: Main.cpp
	$(CXX) $(CFLAGS_WINRELEASE) $(INC_WINRELEASE) -c Main.cpp -o $(OBJDIR_WINRELEASE)/Main.o

clean_winrelease: 
	rm -f $(OBJ_WINRELEASE) $(OUT_WINRELEASE)
	rm -rf ./GAME
	rm -rf $(OBJDIR_WINRELEASE)

before_minedbg: 
	test -d ./GAME || mkdir -p ./GAME
	test -d $(OBJDIR_MINEDBG) || mkdir -p $(OBJDIR_MINEDBG)

after_minedbg: 

minedbg: before_minedbg out_minedbg after_minedbg

out_minedbg: before_minedbg $(OBJ_MINEDBG) $(DEP_MINEDBG)
	$(LD) $(LIBDIR_MINEDBG) -o $(OUT_MINEDBG) $(OBJ_MINEDBG)  $(LDFLAGS_MINEDBG) $(LIB_MINEDBG)

$(OBJDIR_MINEDBG)/Main.o: Main.cpp
	$(CXX) $(CFLAGS_MINEDBG) $(INC_MINEDBG) -c Main.cpp -o $(OBJDIR_MINEDBG)/Main.o

clean_minedbg: 
	rm -f $(OBJ_MINEDBG) $(OUT_MINEDBG)
	rm -rf ./GAME
	rm -rf $(OBJDIR_MINEDBG)

before_minerel: 
	test -d ./GAME || mkdir -p ./GAME
	test -d $(OBJDIR_MINEREL) || mkdir -p $(OBJDIR_MINEREL)

after_minerel: 

minerel: before_minerel out_minerel after_minerel

out_minerel: before_minerel $(OBJ_MINEREL) $(DEP_MINEREL)
	$(LD) $(LIBDIR_MINEREL) -o $(OUT_MINEREL) $(OBJ_MINEREL)  $(LDFLAGS_MINEREL) $(LIB_MINEREL)

$(OBJDIR_MINEREL)/Main.o: Main.cpp
	$(CXX) $(CFLAGS_MINEREL) $(INC_MINEREL) -c Main.cpp -o $(OBJDIR_MINEREL)/Main.o

clean_minerel: 
	rm -f $(OBJ_MINEREL) $(OUT_MINEREL)
	rm -rf ./GAME
	rm -rf $(OBJDIR_MINEREL)

before_1_7_3_debug: 
	test -d .. || mkdir -p ..
	test -d $(OBJDIR_1_7_3_DEBUG) || mkdir -p $(OBJDIR_1_7_3_DEBUG)

after_1_7_3_debug: 

1_7_3_debug: before_1_7_3_debug out_1_7_3_debug after_1_7_3_debug

out_1_7_3_debug: before_1_7_3_debug $(OBJ_1_7_3_DEBUG) $(DEP_1_7_3_DEBUG)
	$(LD) $(LIBDIR_1_7_3_DEBUG) -o $(OUT_1_7_3_DEBUG) $(OBJ_1_7_3_DEBUG)  $(LDFLAGS_1_7_3_DEBUG) $(LIB_1_7_3_DEBUG)

$(OBJDIR_1_7_3_DEBUG)/Main.o: Main.cpp
	$(CXX) $(CFLAGS_1_7_3_DEBUG) $(INC_1_7_3_DEBUG) -c Main.cpp -o $(OBJDIR_1_7_3_DEBUG)/Main.o

clean_1_7_3_debug: 
	rm -f $(OBJ_1_7_3_DEBUG) $(OUT_1_7_3_DEBUG)
	rm -rf ..
	rm -rf $(OBJDIR_1_7_3_DEBUG)

virtual_all: linux_debug linux_release

.PHONY: before_linux_debug after_linux_debug clean_linux_debug before_linux_release after_linux_release clean_linux_release before_windebug after_windebug clean_windebug before_winrelease after_winrelease clean_winrelease before_minedbg after_minedbg clean_minedbg before_minerel after_minerel clean_minerel before_1_7_3_debug after_1_7_3_debug clean_1_7_3_debug

